<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.26">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>subject3-2025-2-extracted</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-587c61ba64f3a5504c4d52d930310e48.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-1d4f84655f446305ac42a8f1abcf7405.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


</head>

<body class="fullcontent quarto-light">

<div id="quarto-search-results"></div>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="某零售企業建立一個銷售預測模型希望評估該模型在不同月份的新資料" class="level3">
<h3 class="anchored" data-anchor-id="某零售企業建立一個銷售預測模型希望評估該模型在不同月份的新資料">1. 某零售企業建立一個銷售預測模型，希望評估該模型在不同月份的新資料</h3>
<p>上，是否仍能維持穩定的預測表現。資料科學團隊計畫利用統計方法檢驗 模型對未觀察資料的適應能力與泛化效果。下列哪一種方法最適合用於此 目的？ (A) F 檢定（F-test）； (B) 交叉驗證（Cross-Validation）； (C) 配對樣本 t 檢定（Paired-sample t-test）； (D) 卡方檢定（Chi-square Test）</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="在建立迴歸或分類模型時若希望避免模型過度擬合overfitting-可" class="level3">
<h3 class="anchored" data-anchor-id="在建立迴歸或分類模型時若希望避免模型過度擬合overfitting-可">2. 在建立迴歸或分類模型時，若希望避免模型過度擬合（Overfitting） ，可</h3>
<p>透過加入正則化項以限制模型的複雜度。其中，L1 正則化（Lasso）的主 要效果為何？ (A) 增加模型參數的數量，以提升表現靈活度； (B) 強化梯度穩定性，避免參數更新過度震盪； (C) 產生稀疏模型（Sparse Model） ，使部分參數權重收斂為零； (D) 提高學習率（Learning Rate） ，加速模型收斂速度</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="在訓練非線性模型時若目標函數為非凸函數non-convex-function" class="level3">
<h3 class="anchored" data-anchor-id="在訓練非線性模型時若目標函數為非凸函數non-convex-function">3. 在訓練非線性模型時，若目標函數為非凸函數（Non-convex Function），</h3>
<p>演算法在參數更新過程中可能出現多個極值點，導致最佳化結果不穩定。 請問此時最可能發生下列哪一種情況？ (A) 梯度消失； (B) 資料過少； (C) 局部最優解； (D) 過擬合</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="在執行-dbscandensity-based-spatial-clustering-of-applications" class="level3">
<h3 class="anchored" data-anchor-id="在執行-dbscandensity-based-spatial-clustering-of-applications">4. 在執行 DBSCAN（Density-Based Spatial Clustering of Applications</h3>
<p>with Noise）群集分析時，若某資料點鄰域內的樣本數不足以形成核心點 （Core Point） ，且該點未被任何核心點的鄰域所包含，也未與其他群集形 成密度可達關係（Density Reachability） ，此資料點最終將被歸類為哪一 種類型？ (A) 鄰近點（Neighbor Point）； (B) 雜訊點（Noise Point）； (C) 邊界點（Border Point）； (D) 潛在點（Potential Point）</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="某智慧製造公司開發一套影像辨識系統用於自動檢測生產線上的瑕疵產" class="level3">
<h3 class="anchored" data-anchor-id="某智慧製造公司開發一套影像辨識系統用於自動檢測生產線上的瑕疵產">5. 某智慧製造公司開發一套影像辨識系統，用於自動檢測生產線上的瑕疵產</h3>
<p>品。系統採用卷積神經網路（Convolutional Neural Network, CNN）作為 主要模型架構，其中第一層卷積層（Convolutional Layer）主要負責的功 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 能為下列何者？ (A) 自動提取輸入影像中的局部特徵； (B) 降低影像維度以加速運算效率； (C) 增加神經元與參數數量以提升模型容量； (D) 整合所有特徵並輸出最終分類結果</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="某智慧城市團隊開發一套交通監控系統用於即時辨識路口監視器影像中" class="level3">
<h3 class="anchored" data-anchor-id="某智慧城市團隊開發一套交通監控系統用於即時辨識路口監視器影像中">6. 某智慧城市團隊開發一套交通監控系統，用於即時辨識路口監視器影像中</h3>
<p>的車輛與行人。團隊比較後發現，卷積神經網路（Convolutional Neural Network, CNN）在訓練與推論效率上，明顯優於傳統的全連接神經網路 （Fully Connected Neural Network, FCNN） 。請問下列何者為主要原因？ (A) CNN 能自動學習影像的旋轉與比例不變性； (B) CNN 可直接跳過人工特徵提取步驟進行分類； (C) CNN 透過區域感知（Local Receptive Field）與參數共享（Parameter Sharing）機制，降低模型參數量與運算複雜度； (D) CNN 捨棄激勵函數（Activation Function） ，以加快運算速度</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="下列哪一種應用最適合採用長短期記憶網路long-short-term-memory" class="level3">
<h3 class="anchored" data-anchor-id="下列哪一種應用最適合採用長短期記憶網路long-short-term-memory">7. 下列哪一種應用最適合採用長短期記憶網路（Long Short-Term Memory,</h3>
<p>LSTM）模型？ (A) 預測未來七天的電力需求變化趨勢； (B) 辨識監視影像中不同類別的物件； (C) 將大量顧客資料依相似特徵自動分群； (D) 將高維度的感測器資料壓縮成低維表示</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="資訊增益information-gain常用於衡量特徵對分類結果的不確定性貢" class="level3">
<h3 class="anchored" data-anchor-id="資訊增益information-gain常用於衡量特徵對分類結果的不確定性貢">8. 資訊增益（Information Gain）常用於衡量特徵對分類結果的不確定性貢</h3>
<p>獻程度，並據以進行特徵選擇。此方法主要應用於下列哪一類模型架構 中？ (A) 使用 L1 正則化進行特徵篩選的線性模型； (B) 利用激活函數（Activation Function）進行特徵擷取的深度神經網 路； (C) 透過核函數（Kernel Function）將特徵映射至高維空間的分類模型； (D) 透過遞迴分裂方式建立分類規則的決策樹模型</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="在建構以距離為基礎的機器學習模型如-knnsvm時下列哪一項資料" class="level3">
<h3 class="anchored" data-anchor-id="在建構以距離為基礎的機器學習模型如-knnsvm時下列哪一項資料">9. 在建構以距離為基礎的機器學習模型（如 KNN、SVM）時，下列哪一項資料</h3>
<p>前處理方式最為關鍵？ (A) 進行特徵縮放（Feature Scaling） ，使各特徵變數具有相似的數值範 圍； (B) 將連續型特徵變數轉換為類別型變數； (C) 以平均值或中位數進行缺失值補齊； 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 (D) 進行隨機抽樣以平衡資料筆數</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="下列哪一種應用情境最適合導入-automl以提升模型開發效率" class="level3">
<h3 class="anchored" data-anchor-id="下列哪一種應用情境最適合導入-automl以提升模型開發效率">10. 下列哪一種應用情境最適合導入 AutoML，以提升模型開發效率？</h3>
<ol type="A">
<li>公司已有完整的 MLOps 平台與資深資料科學團隊，模型更新採固定流 程；</li>
<li>製造部門的生產良率模型已長期穩定運作，只需定期調整參數；</li>
<li>行銷部門希望在短時間內比較多種顧客流失預測模型，缺乏專職工程師 與時間進行手動建模；</li>
<li>財務部門正在開發高度客製化的信用風險評估模型，需要精細控制特徵 工程與演算法細節</li>
</ol>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="相較於-grid-searchrandom-search-在超參數調整上具備哪一項主要優" class="level3">
<h3 class="anchored" data-anchor-id="相較於-grid-searchrandom-search-在超參數調整上具備哪一項主要優">11. 相較於 Grid Search，Random Search 在超參數調整上具備哪一項主要優</h3>
<p>勢？ (A) 可自動產生模型架構； (B) 可使用更大的訓練集； (C) 避免模型過擬合； (D) 能更有效率搜尋高維參數空間</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="某智慧製造公司開發一套設備故障預測系統利用感測器資料訓練深度神" class="level3">
<h3 class="anchored" data-anchor-id="某智慧製造公司開發一套設備故障預測系統利用感測器資料訓練深度神">12. 某智慧製造公司開發一套設備故障預測系統，利用感測器資料訓練深度神</h3>
<p>經網路（Deep Neural Network, DNN）模型，以提前偵測異常運作跡象。 在訓練過程中，團隊發現模型收斂速度不穩定：有時過快導致過擬合，有 時又遲遲無法達到最佳準確率。開發團隊可以藉由調整下列哪一項超參數 （Hyperparameter）以改善此問題？ (A) 每個神經元的輸出結果； (B) 損失函數（Loss Function）在訓練過程中的梯度變化值（Gradient）； (C) 學習率（Learning Rate） ，控制模型權重更新的速度； (D) 模型在訓練後產生的權重值</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="標籤偏差label-bias通常是因為什麼原因造成" class="level3">
<h3 class="anchored" data-anchor-id="標籤偏差label-bias通常是因為什麼原因造成">13. 標籤偏差(Label Bias)通常是因為什麼原因造成？</h3>
<ol type="A">
<li>訓練資料量過大；</li>
<li>標記資料本身帶有主觀偏見；</li>
<li>模型結構設計不當；</li>
<li>特徵數量設定過多</li>
</ol>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="下列哪一種-ai-應用情境中模型的可解釋性explainability最為關" class="level3">
<h3 class="anchored" data-anchor-id="下列哪一種-ai-應用情境中模型的可解釋性explainability最為關">14. 下列哪一種 AI 應用情境中，模型的可解釋性（Explainability）最為關</h3>
<p>鍵？ (A) 電商平台利用深度學習模型預測用戶的下一次購買時間，以優化推播行 銷策略； (B) 新創公司使用機器學習演算法自動調整廣告出價策略，以提升點擊轉換 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 率； (C) 醫院導入 AI 模型分析病患影像並給出腫瘤惡性可能性，作為臨床醫師 診斷依據； (D) 銀行導入 AI 模型預測客戶流失率，並自動推薦留客優惠方案</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="在線性迴歸模型中若-r²值為-0.85其意義為何" class="level3">
<h3 class="anchored" data-anchor-id="在線性迴歸模型中若-r²值為-0.85其意義為何">15. 在線性迴歸模型中，若 R²值為 0.85，其意義為何？</h3>
<ol type="A">
<li>模型準確率為 85%；</li>
<li>85%的變異可被模型解釋；</li>
<li>預測誤差為 15%；</li>
<li>模型有 85%的信心水準</li>
</ol>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="在二元分類問題中若精確率precision為-0.8召回率recall為" class="level3">
<h3 class="anchored" data-anchor-id="在二元分類問題中若精確率precision為-0.8召回率recall為">16. 在二元分類問題中，若精確率（Precision）為 0.8，召回率（Recall）為</h3>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="則-f1-分數f1-score為何" class="level3">
<h3 class="anchored" data-anchor-id="則-f1-分數f1-score為何">0. 6，則 F1 分數（F1 Score）為何？</h3>
<ol type="A">
<li>0.686；</li>
<li>0.700；</li>
<li>0.720；</li>
<li>0.750</li>
</ol>
<hr>
</section>
<section id="下列哪一種優化演算法內建動量momentum的設計機制" class="level3">
<h3 class="anchored" data-anchor-id="下列哪一種優化演算法內建動量momentum的設計機制">17. 下列哪一種優化演算法內建動量（Momentum）的設計機制？</h3>
<ol type="A">
<li>SGD+Momentum；</li>
<li>Adam；</li>
<li>RMSProp；</li>
<li>Adagrad</li>
</ol>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="下列何者最能同時反映-xgboostextreme-gradient-boosting相較於傳" class="level3">
<h3 class="anchored" data-anchor-id="下列何者最能同時反映-xgboostextreme-gradient-boosting相較於傳">18. 下列何者最能同時反映 XGBoost（eXtreme Gradient Boosting）相較於傳</h3>
<p>統梯度提升決策樹（Gradient Boosting Decision Tree, GBDT）的主要技 術改進？ (A) 引入正則化項（Regularization）以抑制過擬合，並支援缺失值自動處 理與並行化訓練； (B) 改以隨機森林（Random Forest）架構取代樹模型以提升準確率； (C) 以類神經網路（Neural Network）取代弱分類器（Weak Learners）； (D) 採用批次正規化（Batch Normalization）技術提升模型穩定性</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="某醫療機構開發疾病早期偵測模型正樣本確診病例僅佔-3在模型" class="level3">
<h3 class="anchored" data-anchor-id="某醫療機構開發疾病早期偵測模型正樣本確診病例僅佔-3在模型">19. 某醫療機構開發疾病早期偵測模型，正樣本（確診病例）僅佔 3%。在模型</h3>
<p>訓練與評估過程中，下列哪一種作法最不適合用於提升對少數類病例的預 測能力？ (A) 使用 SMOTE 過採樣； (B) 調整類別權重； (C) 使用準確率（Accuracy）作為評估指標； 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 (D) 欠採樣多數類(Undersampling the majority class)</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="某電子商務公司為開發商品評論情感分析模型希望模型能捕捉評論中不" class="level3">
<h3 class="anchored" data-anchor-id="某電子商務公司為開發商品評論情感分析模型希望模型能捕捉評論中不">20. 某電子商務公司為開發商品評論情感分析模型，希望模型能捕捉評論中不</h3>
<p>同特徵之間的關聯影響，例如「商品價格」與「顧客滿意度」的互動效 果。下列哪一種特徵工程設計方式最適合用於建立互動特徵（Interaction Features）？ (A) 將單一特徵取平方； (B) 對所有特徵進行對數轉換； (C) 將兩個或多個特徵進行乘積或交互組合； (D) 對特徵進行標準化</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="某語音辨識系統開發團隊採用-transformer-架構為了讓模型能同時理解" class="level3">
<h3 class="anchored" data-anchor-id="某語音辨識系統開發團隊採用-transformer-架構為了讓模型能同時理解">21. 某語音辨識系統開發團隊採用 Transformer 架構，為了讓模型能同時理解</h3>
<p>語音片段中的發音特徵、語速變化與語意脈絡等多層次資訊，團隊在設計 中導入了多頭注意力（Multi-head Attention）機制。請問下列何者為此 機制的主要優點？ (A) 減少模型參數量以降低訓練成本； (B) 加速整體注意力計算過程； (C) 從不同表示子空間（Representation Subspaces）同時捕捉多樣化關聯 資訊； (D) 避免梯度消失（Gradient Vanishing）問題</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="某電商平台希望預測顧客是否會購買特定商品系統蒐集顧客的瀏覽紀" class="level3">
<h3 class="anchored" data-anchor-id="某電商平台希望預測顧客是否會購買特定商品系統蒐集顧客的瀏覽紀">22. 某電商平台希望預測顧客是否會購買特定商品。系統蒐集顧客的瀏覽紀</h3>
<p>錄、停留時間、商品類別偏好與過去購買行為，並以此推估「在觀察到這 些行為特徵的情況下，該顧客會購買的機率」 。若模型採用貝氏定理 （Bayes’Theorem）進行推論，下列敘述何者最符合其核心運作機制？ (A) 根據歷史樣本自動分群，找出行為相似的顧客群； (B) 以條件機率方式計算顧客屬於「會購買」或「不會購買」的分類機率； (C) 以最小平方誤差（Mean Squared Error）為損失函數，預測顧客的購買 金額； (D) 依據回饋信號（Feedback Signal）透過強化學習（Reinforcement Learning）動態調整推薦策略</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="一家再生能源公司希望預測未來三個月太陽能發電量的波動範圍由於氣" class="level3">
<h3 class="anchored" data-anchor-id="一家再生能源公司希望預測未來三個月太陽能發電量的波動範圍由於氣">23. 一家再生能源公司希望預測未來三個月太陽能發電量的波動範圍。由於氣</h3>
<p>候條件具有高度隨機性，且輸入變數（如日照時數、雲量、溫度）之間存 在不確定關係，工程團隊決定以隨機抽樣方式模擬多種可能情境，以估算 整體發電量的機率分佈與風險區間。請問此時所採用的技術最符合下列哪 一種方法？ (A) 蒙地卡羅方法（Monte Carlo Method）； 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 (B) K-means 聚類（K-means Clustering）； (C) 支持向量迴歸（Support Vector Regression, SVR）； (D) 特徵選取（Feature Selection）</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="某房地產公司利用多元迴歸模型multiple-regression-model預測房" class="level3">
<h3 class="anchored" data-anchor-id="某房地產公司利用多元迴歸模型multiple-regression-model預測房">24. 某房地產公司利用多元迴歸模型（Multiple Regression Model）預測房</h3>
<p>價，並繪製殘差圖（Residual Plot）檢查模型品質。結果顯示部分資料點 的殘差極大，且在高價區樣本中出現系統性彎曲分佈現象。根據此觀察， 下列何者為最可能的正確解釋？ (A) 模型過度擬合（Overfitting） ，導致在訓練資料上表現過好、泛化能力 不足； (B) 模型特徵數量不足，導致欠擬合（Underfitting）； (C) 模型存在異常值（Outlier）或非線性關係，違反迴歸假設； (D) 殘差圖呈現隨機分佈，表示模型已完全符合所有假設</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="某金融機構正在建立傳統信用評分卡模型採用邏輯迴歸logistic" class="level3">
<h3 class="anchored" data-anchor-id="某金融機構正在建立傳統信用評分卡模型採用邏輯迴歸logistic">25. 某金融機構正在建立傳統信用評分卡模型，採用邏輯迴歸（Logistic</h3>
<p>Regression）作為建模方法，並依循監理機關建議的標準化流程進行模型 開發。下列哪一項不是傳統信用評分卡模型開發流程中的常見步驟？ (A) 使用生成式模型進行特徵學習； (B) 進行特徵選擇與多重共線性（Multicollinearity）分析； (C) 進行分箱（Binning）與資訊值（Information Value, IV）檢定； (D) 使用樣本穩定性指標（Population Stability Index, PSI）檢驗模型 穩定性</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="在防止監督式學習模型過擬合overfitting時下列哪一種策略不屬於" class="level3">
<h3 class="anchored" data-anchor-id="在防止監督式學習模型過擬合overfitting時下列哪一種策略不屬於">26. 在防止監督式學習模型過擬合（Overfitting）時，下列哪一種策略不屬於</h3>
<p>降低模型複雜度或限制學習能力的作法？ (A) 採用 L1 或 L2 正則化； (B) 在訓練過程中使用 Dropout 技術； (C) 採取早期停止（Early Stopping）機制； (D) 擴增輸入特徵變數以提升模型表達能力</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="某智慧製造團隊在開發瑕疵影像檢測模型時發現使用線性激活函數" class="level3">
<h3 class="anchored" data-anchor-id="某智慧製造團隊在開發瑕疵影像檢測模型時發現使用線性激活函數">27. 某智慧製造團隊在開發瑕疵影像檢測模型時，發現使用線性激活函數</h3>
<p>（Activation Function）後，模型的訓練準確率長期停滯，懷疑模型無法 學習到足夠複雜的特徵表達。若要改善此問題，下列哪一項調整方案最為 合適？ (A) 增加卷積層（Convolutional Layer）數量，使網路更深以強化特徵提 取； (B) 將輸入影像先進行灰階化處理，降低運算量； (C) 使用 Sigmoid 激活函數，以將輸出壓縮至[0,1]範圍； 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 (D) 改用 ReLU（Rectified Linear Unit）激活函數，以引入非線性並提升 模型表達能力</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="一家零售電商公司希望建立顧客流失預測模型用以判斷哪些會員可能在" class="level3">
<h3 class="anchored" data-anchor-id="一家零售電商公司希望建立顧客流失預測模型用以判斷哪些會員可能在">28. 一家零售電商公司希望建立顧客流失預測模型，用以判斷哪些會員可能在</h3>
<p>三個月內不再消費。團隊以去年會員資料進行訓練，並僅採用「曾經購買 三次以上」的活躍顧客紀錄作為樣本。模型上線後，對整體會員進行預測 時，發現模型對於新註冊會員與低消費會員的預測準確率明顯偏低。下列 何者為造成此現象最可能的原因？ (A) 特徵設計未排除與會員忠誠度高度相關的變數，導致特徵偏差 （Feature Bias）； (B) 標記（Label）由人工標註，導致標籤偏差（Label Bias）； (C) 訓練樣本僅涵蓋高活躍顧客，造成取樣偏差（Sampling Bias）； (D) 模型未進行超參數調整，導致過擬合（Overfitting）</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="在工業設備故障預測專案中模型訓練與超參數調整均依賴於一段歷史數" class="level3">
<h3 class="anchored" data-anchor-id="在工業設備故障預測專案中模型訓練與超參數調整均依賴於一段歷史數">29. 在工業設備故障預測專案中，模型訓練與超參數調整均依賴於一段歷史數</h3>
<p>據作為驗證集。然而，隨著設備運行環境與工況條件的變化，原有驗證集 已無法充分反映現況，導致模型在實際部署後的預測準確率逐漸下降。下 列哪一種策略最能有效提升模型在長期運行環境中的穩健性與泛化能力？ (A) 固定驗證集內容，並透過模型正則化技巧（如 L2 正則化）強化模型泛 化； (B) 將全部歷史資料納入訓練，不使用驗證集，依靠早期停止（Early Stopping）控制訓練； (C) 簡化模型架構，減少模型參數數量以降低過擬合風險； (D) 採用時間序列交叉驗證（Time Series Cross Validation）或滑動視窗 驗證（Rolling Window Validation）方法，動態更新驗證資料以適應時間 演進</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="某情感分析模型在英文資料集上取得-macro-f1-score-0.91當該模型" class="level3">
<h3 class="anchored" data-anchor-id="某情感分析模型在英文資料集上取得-macro-f1-score-0.91當該模型">30. 某情感分析模型在英文資料集上取得 macro F1-score = 0.91。當該模型</h3>
<p>部署於西班牙文資料集時，F1-score 驟降至 0.58。下列哪一項解釋最合 理，且與 F1-score 變化相關？ (A) macro F1-score 本身波動性高，建議改用 micro-average F1-score 評估； (B) 模型在西班牙文語料上過度擬合，導致評估結果偏高； (C) 語言轉移造成召回率（Recall）下降，模型無法正確辨識關鍵情緒詞 彙； (D) 以均方誤差（MSE）取代 F1-score 評估可獲得更準確的結果</p>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="某能源公司利用歷史氣象與用電資料開發長期電力需求預測模型採用" class="level3">
<h3 class="anchored" data-anchor-id="某能源公司利用歷史氣象與用電資料開發長期電力需求預測模型採用">31. 某能源公司利用歷史氣象與用電資料，開發長期電力需求預測模型，採用</h3>
<p>第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 深度神經網路架構進行訓練。在訓練過程中，模型在訓練集上的損失值持 續下降，但在驗證集上，損失在第 80 輪後開始波動，呈現週期性上升與下 降。團隊懷疑模型受到季節性資料波動與隨機噪音影響，導致驗證損失難 以穩定收斂。若要在此情境下合理運用早期停止法（Early Stopping）以 確保模型具最佳泛化能力，下列哪一項策略最為適當？ (A) 直接根據訓練集損失最低點停止訓練，以確保模型充分擬合所有樣本； (B) 監控驗證集損失並設定適度的耐心值（Patience） ，在連續多輪未改善 後再停止訓練； (C) 改以測試集損失作為早停依據，以提升模型最終評估一致性； (D) 將所有資料重新合併後訓練至收斂，避免因資料分割導致評估波動</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="某電信公司開發客戶流失預測模型使用大量顧客行為特徵例如通話時" class="level3">
<h3 class="anchored" data-anchor-id="某電信公司開發客戶流失預測模型使用大量顧客行為特徵例如通話時">32. 某電信公司開發客戶流失預測模型，使用大量顧客行為特徵，例如通話時</h3>
<p>長、上網頻率、帳單金額、客服聯絡次數等。在訓練過程中，團隊發現部 分特徵彼此高度相關，但同時也懷疑有些特徵對流失預測的貢獻度有限。 若希望模型在避免過擬合（Overfitting）的同時，能自動篩選出較具代表 性的特徵，採用下列哪一種方法最為合適？ (A) 使用早期停止法（Early Stopping）控制訓練回合數，避免過擬合 （Overfitting）； (B) 同時移除多重共線性特徵並採用 L2 正則化（Ridge） ，以確保模型穩定 收斂； (C) 僅使用 L2 正則化（Ridge） ，抑制所有權重幅度但保留全部特徵； (D) 採用 L1 正則化（Lasso） ，透過懲罰項使部分特徵係數縮為0</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="某資料科學團隊正在開發一個客戶相似度比對系統用於計算所有客戶之" class="level3">
<h3 class="anchored" data-anchor-id="某資料科學團隊正在開發一個客戶相似度比對系統用於計算所有客戶之">33. 某資料科學團隊正在開發一個客戶相似度比對系統，用於計算所有客戶之</h3>
<p>間的相似度分數。若系統需逐一比對每一位客戶與其他所有客戶的資料組 合，此時演算法的時間複雜度最可能為哪一種？其代表意義為何？ (A) O(n) — 執行時間與資料量成線性關係； (B) O(n²) — 執行時間與資料量平方成正比； (C) O(1) — 執行時間固定不變； (D) O(log n) — 執行時間與資料量呈對數成長關係</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="某醫療人工智慧團隊正在開發心臟病風險預測模型資料量僅有-150-筆" class="level3">
<h3 class="anchored" data-anchor-id="某醫療人工智慧團隊正在開發心臟病風險預測模型資料量僅有-150-筆">34. 某醫療人工智慧團隊正在開發心臟病風險預測模型，資料量僅有 150 筆，</h3>
<p>其中陽性個案不到 8%。由於樣本數稀少且類別分布極不平衡，團隊希望在 有限資料下，仍能準確評估模型在不同資料上的表現穩定性，同時避免訓 練資料被過度切分而影響模型效能。若團隊希望在有限樣本下，同時兼顧 資料的利用率與各類別在驗證折中的比例一致性，最適合採用下列哪一種 交叉驗證方法？ 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 (A) 5-Fold 交叉驗證（5-Fold Cross Validation）； (B) 留一法交叉驗證（Leave-One-Out Cross Validation）； (C) 隨機交叉驗證（Random Cross Validation）； (D) 分層留一法交叉驗證（Stratified Leave-One-Out Cross Validation）</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="某公司針對製程感測器資料進行主成分分析pca-經標準化與協方差矩" class="level3">
<h3 class="anchored" data-anchor-id="某公司針對製程感測器資料進行主成分分析pca-經標準化與協方差矩">35. 某公司針對製程感測器資料進行主成分分析（PCA） ，經標準化與協方差矩</h3>
<p>陣分解後，得到三個主成分的特徵值如下：λ1=6.0, λ2=3.0, λ3=1.0。 若團隊決定僅保留能解釋至少 80% 總變異量的主成分，以進行後續模型建 構，下列哪一項敘述最合理且數據解讀正確？ (A) 前兩個主成分合計解釋 90%的總變異量，因此可安全降維至二維，且仍 保留大部分資訊； (B) 第一主成分解釋 60%的變異量，表示資料結構呈現明顯線性關係，僅保 留一維即可避免過擬合； (C) 雖然前兩個主成分可解釋超過 80% 變異量，但第二主成分貢獻仍高達 30%，不宜捨棄第三主成分； (D) 三個特徵值相差不大，顯示各主成分變異均衡，降維可能導致資訊損失</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="某銀行計畫與多家合作機構共同訓練一個-ai-信用風險預測模型為避免客" class="level3">
<h3 class="anchored" data-anchor-id="某銀行計畫與多家合作機構共同訓練一個-ai-信用風險預測模型為避免客">36. 某銀行計畫與多家合作機構共同訓練一個 AI 信用風險預測模型，為避免客</h3>
<p>戶交易資料在傳輸與運算過程中外洩，技術團隊評估使用同態加密 （Homomorphic Encryption）技術。下列何者最能正確描述同態加密在此 應用中的關鍵特性？ (A) 系統以隨機雜訊（Noise）干擾輸出，確保統計結果不洩漏個資； (B) 各參與銀行透過安全通道交換私鑰，確保模型參數一致； (C) 將原始資料壓縮並同時加密，以減少加密後資料量與運算時間； (D) 資料在加密狀態下仍可進行數值運算，模型訓練可於未解密資料上完成</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="某跨銀行風控平台希望整合多家銀行的用戶行為資料用於訓練信用風險" class="level3">
<h3 class="anchored" data-anchor-id="某跨銀行風控平台希望整合多家銀行的用戶行為資料用於訓練信用風險">37. 某跨銀行風控平台希望整合多家銀行的用戶行為資料，用於訓練信用風險</h3>
<p>預測模型。由於競爭與法規限制，各銀行僅願意提供加密後資料，且資料 在任何時間不得被平台解密。同時，平台需建立安全通訊協議以確保資料 在傳輸過程未被竄改或重放。 下列哪一組技術最能完整對應上述需求？ (A) 對稱加密（Symmetric Encryption）＋ 單向雜湊（Hash Function）＋ 非對稱加密（Asymmetric Encryption）＋ 差分隱私（Differential Privacy）； (B) 同態加密（Homomorphic Encryption）＋ 非對稱加密（Asymmetric Encryption）＋ 單向雜湊（ One-way Hash Function）＋ 對稱加密 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 （Symmetric Encryption）； (C) 差分隱私（Differential Privacy）＋ 對稱加密（Symmetric Encryption）＋ 同態加密（Homomorphic Encryption）＋ 數位簽章 （Digital Signature）； (D) 同態加密（Homomorphic Encryption）＋ 安全多方計算（Secure Multi-party Computation, MPC）＋ 雜湊函數（Hash Function）＋ 對稱 加密（Symmetric Encryption）</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="附圖程式碼所計算的是哪一類型的評估指標" class="level3">
<h3 class="anchored" data-anchor-id="附圖程式碼所計算的是哪一類型的評估指標">38. 附圖程式碼所計算的是哪一類型的評估指標？</h3>
<ol type="A">
<li>MAE；</li>
<li>MSE；</li>
<li>RMSE；</li>
<li>R²</li>
</ol>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="附圖程式碼實現的是哪一種正則化技術" class="level3">
<h3 class="anchored" data-anchor-id="附圖程式碼實現的是哪一種正則化技術">39. 附圖程式碼實現的是哪一種正則化技術？</h3>
<ol type="A">
<li>L1 正則化；</li>
<li>L2 正則化；</li>
<li>Dropout；</li>
<li>Batch Normalization</li>
</ol>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="依據附圖程式碼進行資料處理下列何者正確" class="level3">
<h3 class="anchored" data-anchor-id="依據附圖程式碼進行資料處理下列何者正確">40. 依據附圖程式碼進行資料處理，下列何者正確？</h3>
<ol type="A">
<li>np.linalg.inv</li>
<li>計算矩陣 A 的行列式；</li>
<li>v1 * v2 結果為 array([5, 7, 9])；</li>
<li>np.dot(v1, v2) 結果為 np.int64(32)；</li>
<li>np.linalg.eig</li>
<li>計算矩陣 A 的反矩陣</li>
</ol>
<p><strong>✅ 答案：(C)</strong></p>
<hr>
</section>
<section id="考慮擲出骰子並採用-monte-carlo-方法估算條件機率參考附圖程式碼" class="level3">
<h3 class="anchored" data-anchor-id="考慮擲出骰子並採用-monte-carlo-方法估算條件機率參考附圖程式碼">41. 考慮擲出骰子並採用 Monte Carlo 方法估算條件機率，參考附圖程式碼。</h3>
<p>第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日</p>
<p>事件 A：擲出偶數 事件 B：擲出大於 3 請問下列何者為條件機率 P(A∣B)的正確值？ (A) A_and_B.sum() / (A.sum() * B.sum())； (B) A_and_B.sum() / (A.sum() + B.sum())； (C) A_and_B.sum() / A.sum()； (D) A_and_B.sum() / B.sum() VGG16 是由牛津大學 Visual Geometry Group(VGG)在 2014 年提出的經典 卷積神經網路（Convolutional Neural Network, CNN）架構。該模型以簡 潔且規則的層堆疊設計聞名，廣泛應用於影像分類、特徵提取及遷移學習 等任務。附圖程式碼載入了預訓練的 VGG16 模型，並輸出其完整層級結構 及參數統計摘要（如附表） 。請根據此資訊回答42~45 題。</p>
<table class="caption-top table">
<colgroup>
<col style="width: 91%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Layer (type) Output Shape Param # ================================================================ Conv2d-1 [-1, 64, 150, 150] 1,792 ReLU-2 [-1, 64, 150, 150] 0 Conv2d-3 [-1, 64, 150, 150] 36,928 ReLU-4 [-1, 64, 150, 150] 0 MaxPool2d-5 [-1, 64, 75, 75] 0 Conv2d-6 [-1, 128, 75, 75] 73,856 ReLU-7 [-1, 128, 75, 75] 0 Conv2d-8 [-1, 128, 75, 75] 147,584</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Input size (MB): 0.26 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 Forward/backward pass size (MB): 96.93 Params size (MB): 527.79 Estimated Total Size (MB): 624.98</td>
</tr>
</tbody>
</table>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="在深度神經網路中不同層的參數量parameter-count差異極大有些" class="level3">
<h3 class="anchored" data-anchor-id="在深度神經網路中不同層的參數量parameter-count差異極大有些">42. 在深度神經網路中，不同層的參數量（parameter count）差異極大。有些</h3>
<p>層雖然數量少但計算量大，有些則相反。了解參數分佈情形，有助於模型 壓縮與遷移學習設計。請問在 VGG16 中，下列何者的參數量最多？ (A) 卷積層(Conv2d)； (B) 全連接層(Linear)； (C) ReLU 激活函數； (D) 池化層(MaxPool2d, AdaptiveAvgPool2d)</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="在神經網路中了解各層的運算量分佈有助於模型壓縮與硬體加速的策" class="level3">
<h3 class="anchored" data-anchor-id="在神經網路中了解各層的運算量分佈有助於模型壓縮與硬體加速的策">43. 在神經網路中，了解各層的運算量分佈，有助於模型壓縮與硬體加速的策</h3>
<p>略設計。請問在 VGG16 中，下列何者運算量(FLOPs)最多？ (A) 卷積層(Conv2d)； (B) 全連接層(Linear)； (C) ReLU 激活函數； (D) 池化層(MaxPool2d, AdaptiveAvgPool2d)</p>
<p><strong>✅ 答案：(A)</strong></p>
<hr>
</section>
<section id="vgg16-層數深且結構規則由多層卷積池化及全連接層組成了解各層" class="level3">
<h3 class="anchored" data-anchor-id="vgg16-層數深且結構規則由多層卷積池化及全連接層組成了解各層">44. VGG16 層數深且結構規則，由多層卷積、池化及全連接層組成。了解各層</h3>
<p>的輸入/輸出維度、參數量及記憶體需求，有助於掌握 CNN 模型的組成邏輯 與實作技巧。根據 VGG16 的模型架構，下列敘述何者正確？ (A) AdaptiveAvgPool2d 的輸出會被攤平後傳入第一個全連接層；由於前一 層池化輸出空間為 4×4，所以第一個線性層的輸入維度是 512×4×4 = 8192； (B) Linear-33（第一個全連接層）報出的 102,764,544 參數只包含權重， 偏差（bias）沒有算在內； (C) 根據列出的「Estimated Total Size (MB) = 624.98」 ，表示訓練此模 型只需大約 625MB 的 GPU 記憶體（包含所有 optimizer state 與梯度） ，所 以一張 1 GB 的 GPU 就足夠訓練； (D) VGG16 包含 13 層卷積層（conv）與 3 層全連接層（FC） ，總參數數目 約為 138,357,544（約 138.36M）</p>
<p><strong>✅ 答案：(D)</strong></p>
<hr>
</section>
<section id="在實務應用中我們常使用遷移學習transfer-learning技巧即載入預" class="level3">
<h3 class="anchored" data-anchor-id="在實務應用中我們常使用遷移學習transfer-learning技巧即載入預">45. 在實務應用中，我們常使用遷移學習(transfer learning)技巧，即載入預</h3>
<p>訓練模型（如 VGG16） ，凍結部分層的參數，只針對特定任務重新訓練最後 幾層，這種做法可節省訓練時間並提升模型效能。假設你要對 VGG16 進行 遷移學習(transfer learning)，希望凍結卷積層的參數，只訓練最後全連 第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 接層(classifier)。下列哪段程式碼寫法正確？ (A) ; (B) ; (C) ; (D) 在郵遞區號自動辨識的研究中，研究人員收集了一份手寫數字影像資料 集，每一張影像為 8×8 的灰階圖片，共包含多個手寫數字樣本。這份資料 集來自 UCI Machine Learning Repository，常被用於數字辨識與機器學 習方法的教學與實驗。 在過程中，研究人員發現資料中可能存在雜訊，例如筆跡模糊或影像中附 加的干擾點，這會影響後續分類模型的效能。因此，他們希望透過資料降 噪的方法，提升後續分類的準確度。同時，他們也想透過 KNN (K-Nearest Neighbors) 搭配交叉驗證來評估模型表現，確保模型在不同資料切割下都 能有穩定的預測能力。</p>
<p>部分樣本經繪製後的外觀如下圖所示：</p>
<p>第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日</p>
<p>根據這份資料來回答 46~47 題。</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="假設研究人員已將含有雜訊的手寫數字影像存放在變數-noisy-中部分資" class="level3">
<h3 class="anchored" data-anchor-id="假設研究人員已將含有雜訊的手寫數字影像存放在變數-noisy-中部分資">46. 假設研究人員已將含有雜訊的手寫數字影像存放在變數 noisy 中。部分資</h3>
<p>料經視覺化後的外觀如下：</p>
<p>他們嘗試使用 PCA 進行降噪，並希望能保留影像的主要特徵，同時去除影 像中的雜訊。然而，當程式執行後，觀察到影像仍然含有明顯的雜訊。研 究人員懷疑是程式中某個步驟的設定不正確，導致 PCA 沒有發揮降噪的作 用，需要修改程式碼才能讓降噪有效。請問哪一段程式碼需要修改，才能 讓 PCA 對 noisy 影像有效去噪？ (A) 程式碼 A； (B) 程式碼 B； (C) 程式碼 C； (D) 程式碼 D</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="研究人員在對-digits-資料集進行分類時決定使用-knn-並搭配交叉驗證來" class="level3">
<h3 class="anchored" data-anchor-id="研究人員在對-digits-資料集進行分類時決定使用-knn-並搭配交叉驗證來">47. 研究人員在對 digits 資料集進行分類時，決定使用 KNN 並搭配交叉驗證來</h3>
<p>評估模型準確率。他們撰寫了四組不同的程式碼來進行 KNN 訓練與交叉驗 證，但不確定哪幾組程式碼能正確執行並輸出準確率。每組程式碼在資料 切割、模型訓練、交叉驗證函數的使用上略有差異，研究人員希望找出可 以正確完成任務的程式碼組合，以確保模型評估的可靠性。</p>
<p>第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日</p>
<p>請問哪幾組程式碼能正確使用 KNN 搭配交叉驗證，對 digits 資料集進行訓 練並輸出準確率？ (A) 程式碼 A、程式碼 B、程式碼 C、程式碼 D； (B) 程式碼 A、程式碼 C； (C) 程式碼 A、程式碼 B； (D) 程式碼 C、程式碼 D 使用鐵達尼號(Titanic)資料集進行多層感知機(Multilayer Perceptron, MLP)分類預測分析，其中 survived 為反應變數(1 表示存活，0 表示死 亡)。附圖程式碼展示資料載入與處理，請根據此資料回答第 48~50 題。</p>
<p>下圖顯示資料集的前 5 筆資料。</p>
<p>第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日</p>
<p><strong>✅ 答案：(B)</strong></p>
<hr>
</section>
<section id="參考下圖程式碼下列何者正確" class="level3">
<h3 class="anchored" data-anchor-id="參考下圖程式碼下列何者正確">48. 參考下圖程式碼，下列何者正確？</h3>
<p>A：X_train -= X_train.mean(axis=0) 將每個訓練集特徵的平均值調整為 0 B：X_train /= X_train.std(axis=0) 將每個訓練集特徵的標準差調整為 0 C：X_train 處理結果會將資料壓縮到 0 和 1 之間 D：標準化結果防止梯度爆炸或消失 E：標準化是屬於特徵選擇(Feature Selection)方法 F：X_train 程式碼應修正為 X_train = X_train.std(axis=0), X_test 程式碼應修正為 X_test = X_test.std(axis=0) (A) A、B、C、D；</p>
<p>第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日 (B) A、E； (C) A、D； (D) A、C、F</p>
<p><strong>✅ 答案：(Ｃ)</strong></p>
<hr>
</section>
<section id="參考下圖執行結果下列何者正確" class="level3">
<h3 class="anchored" data-anchor-id="參考下圖執行結果下列何者正確">49. 參考下圖執行結果，下列何者正確？</h3>
<ol type="A">
<li>activation=“relu”其數學式為 ；</li>
<li>空格 1 值為 110，空格 2 值為 100；</li>
<li>空格 1 值為 100，空格 2 值為 110；</li>
<li>activation=“sigmoid”一般用於多類別分類預測模型</li>
</ol>
<p><strong>✅ 答案：(Ｃ)</strong></p>
<hr>
</section>
<section id="參考下圖執行結果下列何者正確-1" class="level3">
<h3 class="anchored" data-anchor-id="參考下圖執行結果下列何者正確-1">50. 參考下圖執行結果，下列何者正確？</h3>
<p>第三科：機器學習技術與應用 考試日期：114 年 11 月08 日 試題公告日期：114 年 11 月 20 日</p>
<p>A：空格 1 須填入 “b-” B：空格 2 須填入 “b–” C：空格 1 須填入 “r-” D：空格 2 須填入 “r–” E：驗證損失明顯較訓練損失減少更明顯 (A) B、C； (B) A、C、D； (C) A、D； (D) C、D、E</p>
<p>《以下空白》</p>
<p><strong>✅ 答案：(Ｃ)</strong></p>
<hr>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp("https:\/\/perng\.github\.io\/ai-cert\/");
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>