project:
  type: book

book:
  title: "AI 雙認證全攻略：AI 應用規劃師 & 工程素養認證"
  author: "AI仁波切"
  date: "2025-11-20"
  chapters:
    - index.md
    - part1.md
    - part2.md
    - part3.md
    - part4.md
    - part5.md

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
