import yaml
import os

def append_qs(filepath, qs):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)
    if not data: data = {'questions': []}
    if 'questions' not in data: data['questions'] = []
    
    # avoid duplicates by id
    existing_ids = set(q['id'] for q in data['questions'] if 'id' in q)
    new_qs = [q for q in qs if q['id'] not in existing_ids]
    
    data['questions'].extend(new_qs)
    with open(filepath, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

ch4_qs = [
    {"id": 7401, "chapter_title": "OpenClaw 與 Hermes", "section_title": "OpenClaw", "text": "OpenClaw 的核心設計理念中，哪一項最受重視？", "type": "multiple_choice", "options": ["最快運算速度", "雲端資料同步", "個人隱私優先", "社群網路分享"], "correct_index": 2, "explanation": "OpenClaw 強調本地運行，確保使用者隱私。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7402, "chapter_title": "OpenClaw 與 Hermes", "section_title": "OpenClaw", "text": "OpenClaw 推薦的互動介面是什麼？", "type": "multiple_choice", "options": ["全新的專屬網頁介面", "命令列終端機", "使用者既有的通訊 App", "虛擬實境頭戴裝置"], "correct_index": 2, "explanation": "OpenClaw 整合在 Telegram、Discord 等既有工具中。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7403, "chapter_title": "OpenClaw 與 Hermes", "section_title": "OpenClaw", "text": "OpenClaw 的「Heartbeat (心跳)」機制有什麼功用？", "type": "multiple_choice", "options": ["監控電腦 CPU 的溫度變化", "讓代理主動在背景執行任務並回報", "定時重新啟動大型語言模型", "偵測外部駭客的惡意連線"], "correct_index": 1, "explanation": "心跳機制讓代理人具備主動性，可在背景無人值守執行排程。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7404, "chapter_title": "OpenClaw 與 Hermes", "section_title": "Hermes Agent", "text": "Hermes Agent 自稱擁有哪一種獨特的內建機制？", "type": "multiple_choice", "options": ["內建無限長度的上下文", "內建自我改進的學習迴圈", "內建自動產生圖像的能力", "內建無限制的免費 API"], "correct_index": 1, "explanation": "Hermes 宣稱是唯一內建學習迴圈的代理，能從任務中學習。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7405, "chapter_title": "OpenClaw 與 Hermes", "section_title": "Hermes Agent", "text": "在 Hermes 的學習迴圈中，當任務完成後它會做什麼？", "type": "multiple_choice", "options": ["立刻清除所有的短期記憶", "評估解法是否值得封裝成技能", "要求使用者支付加密貨幣", "隨機刪除一個舊有的技能"], "correct_index": 1, "explanation": "Hermes 會反思並將優良解法封裝為技能以供未來重用。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7406, "chapter_title": "OpenClaw 與 Hermes", "section_title": "兩者的比較", "text": "Hermes 的技能系統與哪一個開放標準相容？", "type": "multiple_choice", "options": ["OpenAI Plugins", "agentskills.io", "MCP Protocol", "JSON Schema"], "correct_index": 1, "explanation": "Hermes 支援 agentskills.io 開放標準，促進跨代理分享。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7407, "chapter_title": "OpenClaw 與 Hermes", "section_title": "Hermes Agent", "text": "Hermes 使用何種方式來建立使用者的持久性檔案？", "type": "multiple_choice", "options": ["透過 Honcho 框架建立使用者建模", "直接讓使用者手動填寫問卷調查", "從外部購買使用者的廣告追蹤紀錄", "分析使用者的鍵盤敲擊頻率與習慣"], "correct_index": 0, "explanation": "Hermes 透過對話逐漸使用 Honcho 建立持久的 USER.md 檔案。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7408, "chapter_title": "OpenClaw 與 Hermes", "section_title": "Hermes Agent", "text": "對於複雜任務，Hermes 會如何處理？", "type": "multiple_choice", "options": ["直接回報任務失敗以節省資源", "要求使用者自行手動將任務拆解", "派生多個子代理 (Subagents) 並行處理", "交給其他競爭對手的 AI 模型處理"], "correct_index": 2, "explanation": "Hermes 支援並行派生子代理來高效率解決複雜多步驟任務。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7409, "chapter_title": "OpenClaw 與 Hermes", "section_title": "兩者的比較", "text": "在模型選擇上，Hermes 和 OpenClaw 的共通點是？", "type": "multiple_choice", "options": ["只能使用 OpenAI 提供的模型", "都是模型無關 (Model Agnostic) 的", "只能在離線環境下使用開源模型", "必須依賴特定的硬體加速晶片"], "correct_index": 1, "explanation": "兩者都設計為可自由切換不同的底層語言模型。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7410, "chapter_title": "OpenClaw 與 Hermes", "section_title": "設計趨勢", "text": "從 OpenClaw 與 Hermes 可以觀察到 AI 代理的哪一種發展趨勢？", "type": "multiple_choice", "options": ["完全取代傳統圖形使用者介面", "讓 AI 主動接入使用者已有的環境", "強制使用者學習全新的程式語言", "放棄使用任何形式的長期記憶"], "correct_index": 1, "explanation": "代理正逐漸融入人們常用的通訊軟體與工作環境中。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7411, "chapter_title": "OpenClaw 與 Hermes", "section_title": "Hermes Agent", "text": "Hermes 內建的排程功能支援什麼樣的操作方式？", "type": "multiple_choice", "options": ["必須撰寫複雜的 Python 腳本", "只能使用滑鼠點擊圖形化選單", "支援使用自然語言直接定義排程", "必須手動修改作業系統的登錄檔"], "correct_index": 2, "explanation": "使用者可以直接用自然語言設定任務排程（如每天早上八點...）。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7412, "chapter_title": "OpenClaw 與 Hermes", "section_title": "OpenClaw", "text": "OpenClaw 在處理本地檔案時最大的優勢是？", "type": "multiple_choice", "options": ["能把檔案快速備份到公有雲", "不須上傳資料即可在本地整理文件", "能自動破解受密碼保護的檔案", "能自動將所有文件翻譯成英文"], "correct_index": 1, "explanation": "OpenClaw 在本地運行，能在不暴露隱私的情況下處理本地檔案。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7413, "chapter_title": "OpenClaw 與 Hermes", "section_title": "兩者的比較", "text": "這兩個專案對於「記憶」的態度為何？", "type": "multiple_choice", "options": ["認為記憶只會降低系統的效能", "將持久記憶視為代理的核心競爭力", "建議只使用系統預設的短期記憶", "認為只有人類才需要擁有記憶"], "correct_index": 1, "explanation": "沒有記憶的代理無法成為稱職助理，持久記憶是未來發展關鍵。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7414, "chapter_title": "OpenClaw 與 Hermes", "section_title": "Hermes Agent", "text": "Hermes 的「主動記憶管理」是指什麼？", "type": "multiple_choice", "options": ["自動幫電腦增加虛擬記憶體空間", "代理會主動把重要知識寫入記憶", "強制使用者每小時覆誦一次重點", "自動刪除超過三天的所有對話"], "correct_index": 1, "explanation": "Hermes 不需要使用者特別指示，也能主動分辨並保存關鍵資訊。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7415, "chapter_title": "OpenClaw 與 Hermes", "section_title": "OpenClaw", "text": "OpenClaw 如何應對反覆出現的相同任務？", "type": "multiple_choice", "options": ["每次都從頭開始重新推理一次", "自動將解法封裝成新技能以重用", "直接拒絕執行並要求使用者自己做", "將任務外包給網路上的其他代理"], "correct_index": 1, "explanation": "OpenClaw 能自己寫技能，將反覆任務的解法固定下來。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7416, "chapter_title": "OpenClaw 與 Hermes", "section_title": "兩者的比較", "text": "在擴展方式上，OpenClaw 和 Hermes 有何不同？", "type": "multiple_choice", "options": ["前者無法擴展，後者支援無限擴展", "兩者都僅依賴原廠提供的官方外掛", "兩者皆擁抱社群與開放的擴展標準", "前者需要付費，後者完全免費"], "correct_index": 2, "explanation": "兩者都非常重視開源社群，並支援 MCP 或 agentskills 擴展。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7417, "chapter_title": "OpenClaw 與 Hermes", "section_title": "Hermes Agent", "text": "Hermes 的跨會話記憶是透過什麼技術實現的？", "type": "multiple_choice", "options": ["全文搜尋結合大型語言模型的摘要", "依賴使用者手動為對話加上標籤", "將所有對話無限制地塞入上下文", "使用外部的付費商業搜尋引擎"], "correct_index": 0, "explanation": "透過搜尋與摘要技術，Hermes 能在海量歷史中找到相關脈絡。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7418, "chapter_title": "OpenClaw 與 Hermes", "section_title": "OpenClaw", "text": "OpenClaw 可以透過什麼方式執行電腦上的命令列操作？", "type": "multiple_choice", "options": ["只能透過虛擬機器沙盒進行", "直接替使用者跑 shell 指令或腳本", "必須要有管理員的圖形介面授權", "只能執行經過官方數位簽章的指令"], "correct_index": 1, "explanation": "OpenClaw 具備底層操作能力，能代為執行本地終端機指令。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7419, "chapter_title": "OpenClaw 與 Hermes", "section_title": "設計趨勢", "text": "開放標準（如 agentskills.io）為 AI 代理帶來了什麼好處？", "type": "multiple_choice", "options": ["讓所有的代理都長得一模一樣", "讓技能可以跨代理框架互相共享", "強制所有開發者使用相同的程式語言", "讓代理的執行速度獲得十倍提升"], "correct_index": 1, "explanation": "標準化讓不同框架開發出來的工具可以互相移植與重用。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
    {"id": 7420, "chapter_title": "OpenClaw 與 Hermes", "section_title": "兩者的比較", "text": "相較於 OpenClaw，Hermes 更適合哪一種使用者？", "type": "multiple_choice", "options": ["只在乎隱私且從不連上網路的人", "希望 AI 能從工作中持續學習改進的人", "電腦硬體配備極度老舊與低階的人", "只想要一個簡單的氣象播報機器人"], "correct_index": 1, "explanation": "Hermes 的核心優勢在於自我學習與進化，適合進階的生產力使用者。", "tags": ["chap-m5-ch4"], "usage": "quiz"},
]

ch5_qs = [
    {"id": 7510, "chapter_title": "多代理系統與未來發展", "section_title": "代理通訊協議", "text": "在 A2A 協議中，「工作產物 (Artifact)」的主要功用是什麼？", "type": "multiple_choice", "options": ["作為代理人之間的身份驗證金鑰", "封裝遠端代理人完成任務後的回傳結果", "記錄系統中所有發生過的錯誤訊息", "定義代理人可使用的最大記憶體容量"], "correct_index": 1, "explanation": "Artifact 包含了代理人的工作結果與相關描述，便於協調者整合。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7511, "chapter_title": "多代理系統與未來發展", "section_title": "代理通訊協議", "text": "A2A 協議的「事件佇列 (Event Queue)」設計是為了解決什麼問題？", "type": "multiple_choice", "options": ["防止因任務執行過久導致連線過早中斷", "強制代理人只能按照順序逐一執行任務", "讓代理人能夠自動備份所有的對話紀錄", "加速大型語言模型在生成文字時的速度"], "correct_index": 0, "explanation": "事件佇列處理長時間運行的狀態更新，確保連線的穩定性。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7512, "chapter_title": "多代理系統與未來發展", "section_title": "自然語言網路 (NLWeb)", "text": "自然語言網路 (NLWeb) 的核心目標是什麼？", "type": "multiple_choice", "options": ["將所有實體網站自動轉換為手機應用程式", "為任何網站提供自然語言介面以供 AI 互動", "完全取代網際網路現有的通訊加密協定", "禁止未經授權的 AI 模型爬取網站的內容"], "correct_index": 1, "explanation": "NLWeb 旨在讓網站具備被代理人輕易理解與操作的自然語言介面。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7513, "chapter_title": "多代理系統與未來發展", "section_title": "自然語言網路 (NLWeb)", "text": "在 NLWeb 架構中，網站內容是如何被儲存以便快速檢索的？", "type": "multiple_choice", "options": ["全數轉換為高解析度圖片進行視覺辨識", "透過嵌入模型轉換為向量並存入資料庫", "直接將 HTML 原始碼儲存在關聯式資料庫", "印成實體紙本並由人工進行手動建檔"], "correct_index": 1, "explanation": "向量資料庫能高效儲存與檢索具有語意特徵的網站內容。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7514, "chapter_title": "多代理系統與未來發展", "section_title": "自然語言網路 (NLWeb)", "text": "每個 NLWeb 實例同時也是一個什麼伺服器？", "type": "multiple_choice", "options": ["高效能的區塊鏈節點伺服器", "標準化的 MCP 伺服器端點", "負責寄發廣告的郵件伺服器", "儲存多媒體檔案的串流伺服器"], "correct_index": 1, "explanation": "NLWeb 整合了 MCP，讓代理人能透過標準化協定查詢網站資料。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7515, "chapter_title": "多代理系統與未來發展", "section_title": "多代理協作模式", "text": "在「協調者-執行者」模式中，若主任務十分複雜，協調者會怎麼做？", "type": "multiple_choice", "options": ["直接宣告任務失敗並停止運作", "自行花費大量時間獨立完成任務", "將任務拆分為子任務並發配給執行者", "要求使用者提供更為簡單的指令"], "correct_index": 2, "explanation": "協調者的核心價值在於拆解與分派任務，讓專業代理各司其職。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7516, "chapter_title": "多代理系統與未來發展", "section_title": "多代理系統概述", "text": "為何多代理系統能夠完成單一大型模型難以做到的複雜工作？", "type": "multiple_choice", "options": ["因為多代理系統可以完全不受到物理硬體的限制", "多個代理人共同分攤了上下文，突破單一視窗限制", "因為多代理系統必定使用最昂貴的付費模型 API", "多代理系統能自動幫人類寫出完美無瑕的程式碼"], "correct_index": 1, "explanation": "每個代理有自己獨立的上下文，整體系統能處理更龐大的資訊。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7517, "chapter_title": "多代理系統與未來發展", "section_title": "多代理協作模式", "text": "「辯論模式 (Debate)」在設計上能有效減少什麼問題？", "type": "multiple_choice", "options": ["系統執行的整體耗費時間", "代理人的偏見與邏輯盲點", "消耗的雲端運算資源成本", "網路連線的潛在延遲問題"], "correct_index": 1, "explanation": "透過不同代理從正反兩面交互詰問，能有效揭露邏輯盲點與偏見。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7518, "chapter_title": "多代理系統與未來發展", "section_title": "代理安全與信任", "text": "當代理人讀取惡意網頁並受到「提示注入攻擊」時，最危險的後果是？", "type": "multiple_choice", "options": ["代理人會突然開始說出不同的語言", "代理人被誘騙執行非預期的危險操作", "代理人的記憶體會瞬間被無意義資料塞滿", "代理人會自動刪除自身的語言模型權重"], "correct_index": 1, "explanation": "注入攻擊的目標是掌控代理人的行為，利用其權限進行不當操作。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7519, "chapter_title": "多代理系統與未來發展", "section_title": "代理安全與信任", "text": "設立「執行預算 (Execution Budget)」是為了解決什麼潛在風險？", "type": "multiple_choice", "options": ["防止代理人因為陷入無限迴圈而過度消耗資源", "限制代理人存取網路上的某些受版權保護的內容", "強制代理人只能在上班時間進行運算與資料處理", "確保代理人每次回應的字數都能維持在一定範圍"], "correct_index": 0, "explanation": "預算機制能確保系統在失控時及時止損，控制成本與運算資源。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7520, "chapter_title": "多代理系統與未來發展", "section_title": "AI 代理技術的未來趨勢", "text": "電腦使用代理 (Computer Use Agent) 的運作方式類似於什麼？", "type": "multiple_choice", "options": ["一個只能夠處理文字指令的傳統聊天機器人系統", "如同人類般透過視覺辨識螢幕並控制滑鼠與鍵盤", "一個隱藏在背景負責自動備份資料的批次執行檔", "一個專門用來阻擋惡意軟體入侵的系統防火牆"], "correct_index": 1, "explanation": "這類代理不依賴 API，而是透過像素級視覺與 GUI 直接互動。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7521, "chapter_title": "多代理系統與未來發展", "section_title": "代理安全與信任", "text": "在「人機協同 (Human-in-the-loop)」機制中，人類扮演什麼角色？", "type": "multiple_choice", "options": ["只負責提供運算資源與繳交系統維護費用", "在代理人執行關鍵或具破壞性操作前進行授權", "負責手動替代理人撰寫每一行底層的程式碼", "只能被動地觀看代理人執行完畢後的結果報告"], "correct_index": 1, "explanation": "人類作為安全守門員，負責在關鍵決策節點上給予授權與監督。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7522, "chapter_title": "多代理系統與未來發展", "section_title": "代理安全與信任", "text": "為了落實最小權限原則 (Least Privilege)，系統設計時應該怎麼做？", "type": "multiple_choice", "options": ["給予代理人作業系統的最高管理員權限以防出錯", "僅提供代理人完成當前任務所絕對需要的最低權限", "將所有的系統密碼直接寫死在代理人的提示詞之中", "要求使用者在每次對話前都重新輸入一次登入密碼"], "correct_index": 1, "explanation": "最小權限原則可降低代理人遭挾持時對系統造成的損害範圍。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7523, "chapter_title": "多代理系統與未來發展", "section_title": "多代理系統概述", "text": "當任務需要高度專業化的知識時，為什麼多代理系統會比單一代理表現更好？", "type": "multiple_choice", "options": ["因為多代理系統可以自動上網搜尋最新的專業論文", "因為可以配置具有不同領域專業與工具的專屬代理", "因為多代理系統必定擁有比單一代理更快的網路連線", "因為多代理系統可以完全不受到任何硬體效能的限制"], "correct_index": 1, "explanation": "分工可以讓特定代理專精於單一領域，提升整體的決策品質。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7524, "chapter_title": "多代理系統與未來發展", "section_title": "代理通訊協議", "text": "A2A 協議解決了多代理系統中的什麼根本問題？", "type": "multiple_choice", "options": ["不同廠商開發的代理人之間無法互相溝通與協作", "單一代理人無法處理超過十萬字的超長上下文內容", "大型語言模型在進行複雜數學運算時的精準度太低", "系統在處理多媒體影音檔案時的運算效能嚴重不足"], "correct_index": 0, "explanation": "通訊標準打破了系統孤島，讓異質代理人能夠建立合作關係。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7525, "chapter_title": "多代理系統與未來發展", "section_title": "AI 代理技術的未來趨勢", "text": "未來 AI 代理朝向邊緣計算 (Edge Computing) 發展的主要動機為何？", "type": "multiple_choice", "options": ["為了讓代理人可以更容易被集中監控與嚴格管理", "降低對雲端的依賴，提升回應速度與保護本地隱私", "為了強迫使用者購買價格更為昂貴的高階硬體設備", "為了讓所有的 AI 模型都能夠被統一部署在同一個地方"], "correct_index": 1, "explanation": "邊緣計算將運算推向裝置端，具有低延遲與高隱私的優勢。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7526, "chapter_title": "多代理系統與未來發展", "section_title": "代理安全與信任", "text": "「沙盒 (Sandbox)」技術在 AI 代理安全中扮演什麼功能？", "type": "multiple_choice", "options": ["提供一個被隔離的環境讓代理執行可能不安全的程式碼", "自動將代理人的記憶體資料備份到一個安全的隱密空間", "用來過濾使用者輸入文字中可能包含的各種不雅詞彙", "強制將代理人的運算效能限制在一個非常低下的水準"], "correct_index": 0, "explanation": "沙盒限制了程式執行的影響範圍，防止惡意操作破壞主系統。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7527, "chapter_title": "多代理系統與未來發展", "section_title": "多代理系統概述", "text": "建構多代理系統時，開發者最常面臨的挑戰是什麼？", "type": "multiple_choice", "options": ["找不到任何可以免費使用的大型語言模型 API", "如何設計代理人間的溝通機制與維持整體系統的一致性", "使用者的電腦通常缺乏足夠的硬碟空間來儲存系統日誌", "代理人之間的運算速度過快導致人類無法看清楚執行過程"], "correct_index": 1, "explanation": "多代理系統的難點在於協作、通訊與避免代理人間發生衝突。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7528, "chapter_title": "多代理系統與未來發展", "section_title": "自然語言網路 (NLWeb)", "text": "NLWeb 如何處理網站原本複雜的導覽選單與點擊流程？", "type": "multiple_choice", "options": ["強制使用者必須先觀看一段教學影片才能開始瀏覽", "將其簡化為直接的自然語言對話與結構化的資料查詢", "要求網站管理員必須全部重新設計一套全新的圖形介面", "將所有的選單按鈕轉換為代理人無法辨識的隨機圖形"], "correct_index": 1, "explanation": "自然語言介面讓使用者與代理人能跨越層層選單直接獲取目標。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
    {"id": 7529, "chapter_title": "多代理系統與未來發展", "section_title": "代理安全與信任", "text": "代理人若擁有撰寫與執行程式碼的能力，最主要的風險在於？", "type": "multiple_choice", "options": ["會導致作業系統的圖形介面變得非常不穩定與容易當機", "可能會意外寫出具有破壞性或被惡意利用的腳本", "會佔用過多的網路頻寬導致使用者無法正常上網", "會自動刪除系統中所有不是由 AI 所產生的原始程式碼"], "correct_index": 1, "explanation": "程式碼執行權限極高，若未加限制，可能對系統造成嚴重危害。", "tags": ["chap-m5-ch5"], "usage": "quiz"},
]

append_qs('chapter4.yaml', ch4_qs)
append_qs('chapter5.yaml', ch5_qs)
print("Finished appending 4 and 5")
