import yaml
import os

def append_qs(filepath, qs):
    with open(filepath, 'r', encoding='utf-8') as f:
        data = yaml.safe_load(f)
    if not data: data = {'questions': []}
    if 'questions' not in data: data['questions'] = []
    
    # avoid duplicates by id
    existing_ids = set(q['id'] for q in data['questions'] if 'id' in q)
    new_qs = [q for q in qs if q['id'] not in existing_ids]
    
    data['questions'].extend(new_qs)
    with open(filepath, 'w', encoding='utf-8') as f:
        yaml.dump(data, f, allow_unicode=True, sort_keys=False)

ch1_qs = [
    {"id": 7109, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人的組成架構", "text": "代理人架構中「短期記憶」主要對應於什麼？", "type": "multiple_choice", "options": ["外部獨立部署的專屬向量資料庫系統", "大型語言模型的當前對話上下文視窗", "代理人執行腳本中的固定區域變數表", "用來指導代理人行為的核心系統提示詞"], "correct_index": 1, "explanation": "短期記憶受限於模型的上下文視窗，保存近期的對話互動。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7110, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人的組成架構", "text": "代理人架構中「長期記憶」最常依賴的儲存技術是？", "type": "multiple_choice", "options": ["電腦處理器內建的高速快取記憶體", "透過嵌入模型轉換的向量資料庫系統", "傳統的關聯式資料庫與表格結構儲存", "系統環境變數與暫存檔案的動態讀寫"], "correct_index": 1, "explanation": "向量資料庫能將過往知識轉換為向量，實現跨任務的語意檢索。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7111, "chapter_title": "AI 代理人基礎概念", "section_title": "代理推理迴圈", "text": "Plan-and-Execute 模式在處理任務時的主要優勢是什麼？", "type": "multiple_choice", "options": ["反應速度極快且無延遲", "適合處理步驟明確的任務", "不需依賴外部工具的輔助", "能夠完全避免模型產生幻覺"], "correct_index": 1, "explanation": "該模式將任務一次性拆解為多個步驟，非常適合邏輯清晰且明確的工作。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7112, "chapter_title": "AI 代理人基礎概念", "section_title": "代理推理迴圈", "text": "Plan-and-Execute 模式在面對何種情況時最容易發生失敗？", "type": "multiple_choice", "options": ["任務內容過於簡單且缺乏挑戰", "執行過程中環境發生突發的變化", "系統需要進行多次的工具函數呼叫", "本地電腦的可用記憶體空間不足時"], "correct_index": 1, "explanation": "由於一開始就制定好所有計畫，一旦執行環境有變，系統往往無法彈性調整。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7113, "chapter_title": "AI 代理人基礎概念", "section_title": "什麼是 AI 代理人", "text": "下列哪一項操作屬於代理人的「感知能力 (Perception)」範疇？", "type": "multiple_choice", "options": ["規劃出完成任務的詳細後續步驟", "讀取使用者的文字輸入與系統日誌", "呼叫外部 API 執行實際的網路請求", "根據執行結果進行自我反省與修正錯誤"], "correct_index": 1, "explanation": "感知能力指的是代理人接收並理解來自外部環境的輸入資訊。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7114, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人的組成架構", "text": "AI 代理人設定中的「Persona (角色設定)」主要目的是什麼？", "type": "multiple_choice", "options": ["強制限制模型執行的最高運算速度", "賦予模型特定的行為邊界與互動風格", "決定系統預設需要掛載多少工具數量", "自動減少每次對話的上下文視窗大小"], "correct_index": 1, "explanation": "角色設定能指導代理人該以何種語氣和態度回應，確保行為符合預期。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7115, "chapter_title": "AI 代理人基礎概念", "section_title": "代理推理迴圈", "text": "Reflexion 框架相對於一般迴圈，加入了什麼關鍵機制？", "type": "multiple_choice", "options": ["任務開始前的詳細步驟規劃", "任務失敗後的自我反省與改進", "將複雜任務分配給其他協作代理", "完全隨機地嘗試各種可用的新方法"], "correct_index": 1, "explanation": "Reflexion 的核心在於遇到失敗時能進行反思，並將經驗保留給後續嘗試。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7116, "chapter_title": "AI 代理人基礎概念", "section_title": "代理推理迴圈", "text": "在 Reflexion 框架中，代理人自我反省的結果通常會如何被儲存？", "type": "multiple_choice", "options": ["作為短期記憶區塊中的一次性變數", "轉化為長期記憶庫中的歷史經驗紀錄", "直接寫入系統的底層錯誤日誌檔案中", "備份到使用者個人的雲端硬碟儲存空間"], "correct_index": 1, "explanation": "反省結果會被存入記憶體中，讓代理人未來面對類似任務時能避開錯誤。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7117, "chapter_title": "AI 代理人基礎概念", "section_title": "代理推理迴圈", "text": "「後設認知 (Metacognition)」賦予代理人哪一種關鍵能力？", "type": "multiple_choice", "options": ["產生出更快的文字串流生成速度", "自主偵測行為缺陷並主動修正錯誤", "能夠自動產生出全新的後端程式碼", "繞過底層安全機制以獲取最高權限"], "correct_index": 1, "explanation": "後設認知讓代理人能「思考自己的思考過程」，進而達到修正錯誤與適應環境。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7118, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人類型", "text": "Agentic RAG 與傳統的 Naive RAG 最大的區別在於什麼？", "type": "multiple_choice", "options": ["向量資料庫能容納的整體資料容量大小", "代理人是否能主動決定何時進行資料檢索", "伺服器回傳檢索結果的速度快慢差異", "系統底層是否依賴強大的向量嵌入模型"], "correct_index": 1, "explanation": "Agentic RAG 允許代理人根據當下需求，自主判斷是否需要呼叫檢索工具。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7119, "chapter_title": "AI 代理人基礎概念", "section_title": "Agent 的評估指標", "text": "在評估代理人表現時，「任務成功率」指的是什麼？", "type": "multiple_choice", "options": ["系統成功呼叫所有外部工具的總次數", "代理人最終能順利完成給定目標的比例", "代理人生成回覆時所使用的總文字數量", "代理人運行單一任務所耗費的整體時間"], "correct_index": 1, "explanation": "任務成功率是最直觀的指標，衡量代理人是否能實際解決使用者交付的問題。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7120, "chapter_title": "AI 代理人基礎概念", "section_title": "Agent 的評估指標", "text": "評估代理人時，「工具準確度」主要是用來衡量什麼？", "type": "multiple_choice", "options": ["工具伺服器回應 API 請求的延遲時間", "代理人在各種情境下選擇正確工具的比例", "每個外部工具執行時消耗的雲端運算資源", "外部系統所能支援處理的多國語言數量"], "correct_index": 1, "explanation": "工具準確度關注代理人是否能在對的時機挑選並正確呼叫合適的工具。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7121, "chapter_title": "AI 代理人基礎概念", "section_title": "什麼是 AI 代理人", "text": "當代理人遇到未曾見過的突發情況時，最重要的展現能力是？", "type": "multiple_choice", "options": ["直接中斷執行並回報任務失敗給終端使用者", "基於環境回饋來動態調整策略並尋找替代方案", "隨機挑選系統中任何一個可用的工具進行測試", "忽略所有出現的錯誤訊息並繼續執行既定步驟"], "correct_index": 1, "explanation": "自主性與適應力是代理人的核心，面對變化時能動態調整是其最大價值。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7122, "chapter_title": "AI 代理人基礎概念", "section_title": "什麼是 AI 代理人", "text": "相較於寫死的傳統自動化腳本，AI 代理人的核心優勢是什麼？", "type": "multiple_choice", "options": ["執行過程中絕對不會產生任何系統錯誤", "能夠彈性適應高度不可預測的動態環境", "程式執行的總耗時必定比傳統腳本更快", "系統在運作時完全不需要任何人類監督"], "correct_index": 1, "explanation": "傳統腳本只能處理預先定義好的狀況，而代理人能根據上下文彈性處理未知變化。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7123, "chapter_title": "AI 代理人基礎概念", "section_title": "代理推理迴圈", "text": "在代理人的推理迴圈中，「Action (行動)」階段的主要作用是？", "type": "multiple_choice", "options": ["分析使用者輸入文字背後隱藏的真實意圖", "實際呼叫外部工具或 API 來改變環境狀態", "觀察並記錄環境在指令執行後的回傳結果", "評估自身表現的優劣並將其寫入錯誤日誌"], "correct_index": 1, "explanation": "行動階段是指模型決定好策略後，具體執行工具呼叫來影響外部世界。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7124, "chapter_title": "AI 代理人基礎概念", "section_title": "代理推理迴圈", "text": "在代理人的推理迴圈中，「Observation (觀察)」階段的主要作用是？", "type": "multiple_choice", "options": ["獲取並解析外部工具執行後所回傳的具體結果", "決定下一步應該要呼叫哪一個外部系統的工具", "生成給使用者的最終自然語言對話回覆內容", "將整次對話的完整歷史記錄壓縮備份到雲端"], "correct_index": 0, "explanation": "觀察階段讓代理人能看到剛才行動的結果，作為後續判斷與推理的依據。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7125, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人的組成架構", "text": "下列何者最符合「工作記憶 (Working Memory)」的典型應用場景？", "type": "multiple_choice", "options": ["永遠記住使用者的名字與偏好語言設定", "暫存多步驟計算過程中產生的中間變數", "永久保存過去所有專案任務的歷史經驗", "記錄系統啟動時載入的預設系統提示詞"], "correct_index": 1, "explanation": "工作記憶就像系統的草稿紙，專門用來暫存執行中任務的各種中間狀態。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7126, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人類型", "text": "在多代理 (Multi-Agent) 系統中，不同的代理人通常是如何進行協作的？", "type": "multiple_choice", "options": ["所有代理人共用同一個神經網路模型與內部權重", "代理人透過標準化協議交換訊息以分配並完成任務", "代理人之間互相競爭搶奪系統中有限的運算資源", "代理人會透過直接覆寫對方的短期記憶來傳遞資訊"], "correct_index": 1, "explanation": "多代理系統透過定義明確的通訊協議，讓各自專業的代理人能分工協作。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7127, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人的組成架構", "text": "下列哪一個選項「不屬於」現代 AI 代理人的核心組成要素？", "type": "multiple_choice", "options": ["具備自然語言理解能力的大型語言模型", "只能按照單一路徑執行的固定不變決策樹", "能夠用來影響外部環境的可呼叫外部工具", "用來儲存任務狀態與歷史經驗的記憶系統"], "correct_index": 1, "explanation": "代理人依賴 LLM 動態推理，而非傳統自動化系統所使用的固定決策樹。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
    {"id": 7128, "chapter_title": "AI 代理人基礎概念", "section_title": "代理人的組成架構", "text": "為什麼功能完善的 AI 代理人系統不可或缺「長期記憶」？", "type": "multiple_choice", "options": ["為了讓模型能以更快的速度生成文字對話串流", "為了在跨越多個獨立對話時仍能保留過往經驗", "為了大幅度減少系統呼叫外部 API 的整體次數", "為了能直接取代大型語言模型本身的內部權重"], "correct_index": 1, "explanation": "長期記憶讓代理人能記住使用者的偏好與過往互動，提供更個人化的服務。", "tags": ["chap-m5-ch1"], "usage": "quiz"},
]

ch2_qs = [
    {"id": 7210, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 簡介與設計動機", "text": "MCP (Model Context Protocol) 旨在解決 AI 生態系統中的哪一個痛點？", "type": "multiple_choice", "options": ["訓練最新大型語言模型的整體運算成本過於高昂", "AI 系統與各種外部資料源整合時的嚴重碎片化問題", "本地端執行伺服器時的記憶體管理與分配效率太低", "開發者在設計提示詞工程時面臨的語法難度過於複雜"], "correct_index": 1, "explanation": "隨著工具與資料源激增，MCP 提供標準化協議來消弭 M×N 的客製化整合噩夢。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7211, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 系統架構", "text": "在 MCP 架構中，主要負責管理安全策略與使用者授權決策的元件是？", "type": "multiple_choice", "options": ["直接與伺服器溝通的 MCP 客戶端應用程式", "統籌管理與協調的 MCP 主機 (Host) 系統", "提供具體工具與資源的外部 MCP 伺服器", "負責執行所有推論工作的大型語言模型本身"], "correct_index": 1, "explanation": "MCP 主機 (Host) 控制整個系統的生命週期，並確保使用者在呼叫高風險工具時能進行審核。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7212, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 核心元件", "text": "一個標準的 MCP 伺服器可以同時對外提供哪些核心功能元件？", "type": "multiple_choice", "options": ["工具 (Tools)、資源 (Resources) 與提示範本 (Prompts)", "模型本身的神經網路權重與大量的歷史訓練資料", "針對終端使用者設計的圖形介面與豐富的前端佈景", "底層運作所需的網路伺服器與高效能關聯式資料庫"], "correct_index": 0, "explanation": "MCP 伺服器主要透過暴露工具、資源和提示範本來為代理人擴展能力。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7213, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 核心元件", "text": "MCP 中的「Prompts (提示範本)」所扮演的主要角色是什麼？", "type": "multiple_choice", "options": ["強制模型遵守所有內建的安全規範與禁止事項", "提供標準化的任務起始上下文與可重用的對話模板", "自動記錄使用者過去所輸入過的所有指令與日誌", "在使用者輸入過慢時自動幫忙補齊尚未打完的文字"], "correct_index": 1, "explanation": "提示範本允許伺服器提供預先定義好的工作流程起點，幫助代理人快速進入狀況。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7214, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 傳輸機制", "text": "當我們在本地電腦開發與部署 MCP 伺服器時，最常使用的傳輸機制是？", "type": "multiple_choice", "options": ["適合跨網路存取的 HTTP + SSE 遠端連線傳輸機制", "透過本地子程序建立的 stdio (標準輸入輸出) 管道", "用於即時通訊服務的 WebSockets 雙向資料傳輸協定", "專為微服務架構設計的 gRPC 遠端程序高速呼叫協定"], "correct_index": 1, "explanation": "stdio 傳輸方式安全性高且非常適合本地環境，因為它依賴本機程序的執行權限。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7215, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 簡介與設計動機", "text": "MCP 架構如何顯著提升 AI 代理人的「工具發現」能力？", "type": "multiple_choice", "options": ["讓代理人透過自動爬蟲不斷搜尋網路上的可用 API 工具", "讓伺服器能動態提供可用工具清單與詳細的使用參數說明", "預先將全球所有的工具特徵寫死在大型語言模型的權重中", "強迫使用者在使用前手動輸入所有工具的底層實作原始碼"], "correct_index": 1, "explanation": "MCP 客戶端能直接向伺服器查詢可用清單，代理人因此能動態發掘並使用新工具。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7216, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 系統架構", "text": "為什麼開發者在設計 MCP 伺服器時，應該盡可能保持「輕量級」？", "type": "multiple_choice", "options": ["為了節省使用者電腦上寶貴的硬碟與記憶體儲存空間", "為了專注暴露特定領域的能力並遵循單一職責原則", "為了讓大型語言模型可以直接下載並分析其內部架構", "為了避免被作業系統內建的防毒軟體誤判為惡意程式"], "correct_index": 1, "explanation": "輕量級的伺服器專注於做好一件事情，能提升系統整體的穩定度與易維護性。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7217, "chapter_title": "模型上下文協議 (MCP)", "section_title": "代理人可觀測性與評估", "text": "在系統可觀測性 (Observability) 領域中，「Span」代表什麼意義？", "type": "multiple_choice", "options": ["代理人處理完整個使用者對話任務的總計花費時間", "系統內單一操作或函數執行的具體起始與結束時間區間", "大型語言模型在一次生成過程中所輸出的總字數統計", "系統伺服器在執行複雜推論時記憶體使用的最高峰值"], "correct_index": 1, "explanation": "Span 用來標記與測量特定操作的持續時間，幫助開發者定位效能瓶頸。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7218, "chapter_title": "模型上下文協議 (MCP)", "section_title": "代理人可觀測性與評估", "text": "為 AI 代理人實施儀器化 (Instrumentation) 的最主要好處是什麼？", "type": "multiple_choice", "options": ["能大幅度降低呼叫各大雲端模型 API 的整體使用成本", "讓代理人的內部決策過程與工具呼叫狀況變得完全透明化", "能夠自動偵測並完全修正大型語言模型產生的所有錯誤", "直接取代傳統的軟體單元測試與人工驗收測試標準流程"], "correct_index": 1, "explanation": "透過追蹤系統運作，開發者能洞察代理人的思考邏輯，使「黑箱」模型具備可解釋性。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7219, "chapter_title": "模型上下文協議 (MCP)", "section_title": "代理人可觀測性與評估", "text": "在處理多個工具呼叫時，系統日誌常常變得難以閱讀，引入可觀測性工具可以如何解決？", "type": "multiple_choice", "options": ["將所有的系統日誌全數刪除以節省開發人員的閱讀時間", "透過結構化的追蹤 (Traces) 將日誌與特定的操作上下文綁定", "自動把所有日誌翻譯成更易讀的另一種人類自然語言", "強迫模型在每次操作後都必須用語音播報執行結果"], "correct_index": 1, "explanation": "結構化追蹤可以將錯綜複雜的系統日誌關聯到特定的請求上，大幅簡化除錯難度。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7220, "chapter_title": "模型上下文協議 (MCP)", "section_title": "代理人可觀測性與評估", "text": "當代理人發生非預期行為時，哪一種觀測工具最能有效幫助開發者除錯？", "type": "multiple_choice", "options": ["直接匯出並分析大型語言模型的內部神經網路權重分佈圖", "透過代理人的追蹤日誌 (Traces) 還原當時的決策與環境上下文", "檢查使用者的瀏覽器搜尋記錄以推測其真實的問題意圖", "監控伺服器作業系統的 CPU 佔用率與網路頻寬使用情況"], "correct_index": 1, "explanation": "追蹤日誌能清晰重現代理人收到的提示詞、工具回傳結果與其當時的決策過程。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7221, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 系統架構", "text": "在標準的 MCP 系統架構設計中，Client 和 Server 之間的連線關係是？", "type": "multiple_choice", "options": ["客戶端將訊息向所有伺服器廣播的一對多廣播模式", "每個客戶端應用程式維護與單一伺服器的一對一綁定連線", "多個客戶端共享同一個伺服器狀態的多對多無狀態連線", "多個伺服器輪流服務一個客戶端的多對一輪詢連線模式"], "correct_index": 1, "explanation": "一對一的連線設計簡化了狀態管理，讓客戶端與伺服器間的溝通更加清晰可靠。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7222, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 安全考量", "text": "面對來自大型語言模型 (LLM) 的工具呼叫請求，MCP 伺服器應當採取什麼安全態度？", "type": "multiple_choice", "options": ["百分之百信任所有來自知名 LLM 提供商的工具呼叫參數", "伺服器端必須對所有傳入的參數進行嚴格的驗證與邊界檢查", "將所有可能被呼叫的工具設為公開存取以確保最高相容性", "為了節省運算效能，盡量停用伺服器端所有的日誌記錄功能"], "correct_index": 1, "explanation": "為了防止提示詞注入與幻覺帶來的危害，伺服器絕不可盲目信任 LLM 傳來的資料。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7223, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 簡介與設計動機", "text": "MCP 架構本身是如何促進各種不同的 AI 模型之間的互操作性 (Interoperability) 的？", "type": "multiple_choice", "options": ["透過強制要求世界上所有的模型都必須使用完全相同的內部權重", "透過提供一套標準化的通用介面來描述與呼叫外部工具與資源", "透過將所有競爭對手的模型統一部署在同一台巨大的實體伺服器", "透過設計一個專屬的私有通訊協定讓模型之間可以直接互相通訊"], "correct_index": 1, "explanation": "標準化的介面讓開發者不需修改整合程式碼，就能無痛切換底層使用的語言模型。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7224, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 核心元件", "text": "資源 (Resources) 與工具 (Tools) 最大的本質差異在於？", "type": "multiple_choice", "options": ["資源具備改變外部環境副作用的能力，工具僅能用於靜態讀取", "資源是被動讀取的靜態資料，工具則是由模型主動呼叫的動態操作", "資源需要複雜的非對稱加密傳輸，工具則可以直接使用明文傳輸", "資源只能在本地端電腦上運作，工具則只能部署於雲端伺服器上"], "correct_index": 1, "explanation": "資源是被動讀取的上下文資料，而工具是模型主動決定執行的動態操作。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7225, "chapter_title": "模型上下文協議 (MCP)", "section_title": "代理人可觀測性與評估", "text": "在系統可觀測性資料中的「Event (事件)」，通常被用來記錄什麼樣的資訊？", "type": "multiple_choice", "options": ["整個應用程式啟動到結束所持續數分鐘的長時間運作週期", "系統在某個特定時間點所發生的重要動作、警告或狀態變化", "代理人模型在完成訓練後的完整神經網路權重與參數清單", "執行該次對話任務時伺服器硬碟剩餘可用空間的動態變化"], "correct_index": 1, "explanation": "事件代表瞬間發生的狀態標記，例如「使用者點擊同意」、「API 連線失敗」等。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7226, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 簡介與設計動機", "text": "MCP 作為一個完全開源的協議，為整個 AI 生態圈帶來什麼樣的主要優勢？", "type": "multiple_choice", "options": ["保證使用該協議的所有系統絕對不會被任何惡意駭客入侵", "促進全球開發者社群共同建立豐富且相容的工具伺服器生態", "讓各大企業開發的高階模型可以完全免費且無限制地被使用", "完全免除軟體開發者在維護與更新伺服器程式碼上的任何責任"], "correct_index": 1, "explanation": "開源標準打破了廠商鎖定，吸引更多開發者貢獻相容於 MCP 的通用工具與服務。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7227, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 核心元件", "text": "如果你的 MCP 伺服器需要提供一個「讓代理人讀取本地設定檔」的功能，這個功能應該被定義為？", "type": "multiple_choice", "options": ["MCP Tool (工具)", "MCP Resource (資源)", "MCP Prompt (提示範本)", "MCP Client (客戶端)"], "correct_index": 1, "explanation": "讀取靜態檔案且不改變系統狀態的操作，最適合使用 MCP Resource 來實作。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7228, "chapter_title": "模型上下文協議 (MCP)", "section_title": "MCP 核心元件", "text": "如果你的 MCP 伺服器需要提供一個「幫使用者自動發送電子郵件」的功能，這個功能應該被定義為？", "type": "multiple_choice", "options": ["MCP Tool (工具)", "MCP Resource (資源)", "MCP Prompt (提示範本)", "MCP Client (客戶端)"], "correct_index": 0, "explanation": "發送電子郵件會改變外部環境的狀態（產生副作用），必須實作為 MCP Tool。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
    {"id": 7229, "chapter_title": "模型上下文協議 (MCP)", "section_title": "AI 代理人基礎概念", "text": "在代理人的「思考-行動-觀察循環」中，讓「行動」階段得以具體落實的關鍵技術通常是？", "type": "multiple_choice", "options": ["依賴大型語言模型內部的自我反思與情緒模擬機制", "呼叫由 MCP 或其他類似協議所定義的標準化外部工具", "讀取並重新分析使用者過去數個月來的所有對話歷史", "深入分析本地作業系統內部的 CPU 與記憶體效能瓶頸"], "correct_index": 1, "explanation": "行動階段需要透過工具呼叫的機制，將模型的決策轉化為具體的外部系統操作。", "tags": ["chap-m5-ch2"], "usage": "quiz"},
]

ch3_qs = [
    {"id": 7310, "chapter_title": "Agentic Skills 設計", "section_title": "光靠提示詞，為什麼不夠？", "text": "相較於上下文工程，單純依賴提示詞工程在代理人場景中最大的限制是什麼？", "type": "multiple_choice", "options": ["開發者無法精確控制模型最終生成回應的字數長度與格式", "靜態指令難以應對動態變化且不可預測的外部系統環境", "進階提示詞的撰寫語法對於多數開發者而言過於困難且複雜", "大型語言模型在解析超過一百個字的提示詞時容易發生崩潰"], "correct_index": 1, "explanation": "代理人面對的任務環境隨時在變，靜態的提示詞無法涵蓋所有可能的突發狀況。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7311, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "代理人運作時遇到的「上下文中毒 (Context Poisoning)」是指什麼現象？", "type": "multiple_choice", "options": ["使用者輸入的文字長度大幅超越了系統設定的上下文視窗限制", "錯誤的幻覺資訊進入記憶中並被反覆引用，導致模型陷入邏輯死胡同", "系統遭受到惡意使用者的直接網路攻擊，導致伺服器完全停止運作", "代理人因為安全機制過於嚴格而拒絕讀取任何上下文中的敏感內容"], "correct_index": 1, "explanation": "當錯誤資訊成為後續推理的基礎時，代理人就會不斷做出荒謬或無效的決策。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7312, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "要有效防範「上下文中毒」，系統架構上應該採取哪一種策略最為合適？", "type": "multiple_choice", "options": ["直接將系統容許的上下文總字數限制增加到原來的一百倍以上", "實施嚴格的上下文即時驗證，確保寫入記憶前的資訊是正確的", "為了絕對的資料安全，完全停用代理人的所有長期記憶保存功能", "將所有可能導致衝突的上下文自動翻譯成模型不熟悉的罕見語言"], "correct_index": 1, "explanation": "在資訊被當作事實存入記憶前，透過外部工具進行交叉驗證是防止中毒的關鍵。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7313, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "代理人運作時遇到的「上下文分心 (Context Distraction)」是指什麼現象？", "type": "multiple_choice", "options": ["模型因為過度關注龐大的歷史紀錄而忽略了當前任務的真實指令", "代理人在多個子系統之間頻繁切換導致伺服器網路連線不穩定", "系統的安全過濾機制拒絕執行任何包含潛在風險的工具呼叫請求", "代理人因為無法獲取任何足夠的上下文資訊而無法生成有效回應"], "correct_index": 0, "explanation": "當雜訊過多時，模型的注意力機制會被稀釋，忘記現在最重要應該做什麼事。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7314, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "開發者可以透過什麼技術手段來有效減緩「上下文分心」的問題？", "type": "multiple_choice", "options": ["在每次對話前，都將過去一年的所有歷史對話紀錄完整地提供給模型", "定期使用大語言模型摘要技術，將過長的歷史資訊壓縮成精簡的重點", "為了確保指令清晰，嚴格禁止終端使用者輸入超過十個英文字母的指令", "強制設定系統，讓模型在任何情況下都只能用「是」或「否」來回答問題"], "correct_index": 1, "explanation": "摘要技術能去除冗餘對話，保留核心意義，幫助模型在有限視窗內維持專注。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7315, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "若系統一次性提供 50 個不相關的工具給代理人，導致其呼叫錯誤，這屬於何種失效模式？", "type": "multiple_choice", "options": ["上下文衝突 (Context Clash)", "上下文中毒 (Context Poisoning)", "上下文混淆 (Context Confusion)", "上下文分心 (Context Distraction)"], "correct_index": 2, "explanation": "過多選擇會干擾模型的判斷能力，造成上下文混淆，進而選錯工具。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7316, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "實施「工具掛載管理 (Tool Loadout Management)」的主要目的是什麼？", "type": "multiple_choice", "options": ["讓系統能在背景自動下載並更新所有工具的最新底層程式碼", "透過動態檢索，僅提供給代理人當下任務最相關的少量工具集合", "詳細記錄每個工具在過去一個月內的平均執行時間與效能瓶頸", "嚴格限制普通使用者每天可以呼叫系統中特定工具的總次數上限"], "correct_index": 1, "explanation": "減少不必要的工具干擾，能顯著提升代理人選擇正確工具的準確率。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7317, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "在代理人的推理過程中，「上下文衝突 (Context Clash)」通常是如何發生的？", "type": "multiple_choice", "options": ["系統內剛好存在兩個不同開發者所撰寫且名稱完全一模一樣的工具", "代理人的記憶中同時存在著前後矛盾或邏輯完全相反的使用者指示", "兩個不同功能的代理人為了完成任務，同時搶奪同一個網路連接埠", "系統傳遞的上下文資料格式不符合底層 API 所規定的嚴格 JSON 標準"], "correct_index": 1, "explanation": "矛盾的資訊會讓模型無法判斷哪一個才是真實意圖，導致推理不一致。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7318, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "當面對「上下文衝突」時，下列哪一種做法是有效的解決方案之一？", "type": "multiple_choice", "options": ["提供獨立的暫存區 (Scratchpad) 讓模型有空間先協調與統整衝突資訊", "寫一個程式將所有看起來發生衝突的歷史資訊隨機挑選一個並直接刪除", "不做任何修改，直接把底層模型替換成參數規模大十倍的最新商用版本", "遇到衝突時立即暫停系統所有運作，並發送電子郵件等待人工介入處理"], "correct_index": 0, "explanation": "暫存區賦予代理人額外的運算空間來分析矛盾，最終得出一致的行動方針。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7319, "chapter_title": "Agentic Skills 設計", "section_title": "記憶管理設計", "text": "在記憶管理的設計中，實施「衰減機制 (Fading)」的主要用意為何？", "type": "multiple_choice", "options": ["使距離現在較久遠的歷史記憶在檢索時的權重或重要性自然降低", "將純文字的對話內容自動轉換為多維度的向量格式以利快速比較", "透過加密手段防止未經授權的第三方用戶讀取代理人的敏感資料", "藉由刪除特定字元來加快整體工具執行的伺服器網路反應時間"], "correct_index": 0, "explanation": "衰減機制確保代理人會優先參考使用者近期的狀態或偏好，而非陳舊過時的資訊。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7320, "chapter_title": "Agentic Skills 設計", "section_title": "規劃策略設計", "text": "代理人運用「任務分解 (Task Decomposition)」策略能夠帶來什麼具體好處？", "type": "multiple_choice", "options": ["讓大語言模型在生成文字時的速度與流暢度獲得飛躍性的提升", "將過於複雜且難以一次解決的目標，拆解為數個可受控且單純的小步驟", "大幅減少代理人為了完成任務而呼叫各種外部 API 的總計費用", "從根本上徹底避免模型在撰寫程式碼時產生任何的語法或邏輯錯誤"], "correct_index": 1, "explanation": "拆解任務能降低每一步的認知負擔，讓代理人更容易成功達成最終目標。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7321, "chapter_title": "Agentic Skills 設計", "section_title": "Skill 設計最佳實踐", "text": "在設計 Agentic Skills 的時候，為什麼要盡量確保工具操作具備「冪等性 (Idempotency)」？", "type": "multiple_choice", "options": ["因為這樣可以讓後端工程師在撰寫程式碼的時候看起來更加簡潔優雅", "確保代理人在出錯時多次重複執行相同的操作，也不會產生非預期的副作用", "為了在伺服器端大幅度提升工具底層演算法的整體執行效率與運算速度", "為了讓系統能夠自動偵測並修復使用者在輸入對話時所產生的錯別字"], "correct_index": 1, "explanation": "代理人經常會重試失敗的步驟，冪等性可保證重試過程是安全的。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7322, "chapter_title": "Agentic Skills 設計", "section_title": "Skill 設計最佳實踐", "text": "一個設計優良的技能應該回傳清晰完整的錯誤處理訊息，其最主要的目的為何？", "type": "multiple_choice", "options": ["為了滿足大型企業在軟體開發流程中對於程式碼行數的標準合規性規定", "讓大型語言模型能讀懂失敗的原因，並據此動態調整參數或嘗試其他策略", "刻意隱藏系統底層的實際網路架構，避免遭到外部駭客針對性的惡意攻擊", "讓終端使用者在看到錯誤畫面時，覺得系統非常有禮貌且富有同理心"], "correct_index": 1, "explanation": "錯誤訊息是代理人自我反省的關鍵輸入，沒有清晰的錯誤訊息就無法修正路線。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7323, "chapter_title": "Agentic Skills 設計", "section_title": "工具呼叫機制", "text": "有關於「並行工具呼叫 (Parallel Tool Calling)」的敘述，下列何者是正確的？", "type": "multiple_choice", "options": ["系統會強迫所有的工具都必須嚴格按照英文字母順序依次排隊執行", "代理人能夠在一次的推論回應中，同時觸發並執行多個彼此獨立的工具任務", "這個機制僅適用於那些彼此之間具有高度且嚴格順序依賴的複雜連鎖步驟", "啟用這個機制通常會導致系統處理任務的整體花費時間大幅度地往上增加"], "correct_index": 1, "explanation": "並行工具呼叫省去了多次網路往返的延遲，對於互相獨立的任務能顯著提升效率。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7324, "chapter_title": "Agentic Skills 設計", "section_title": "Skill 設計最佳實踐", "text": "在定義提供給代理人的技能時，為什麼在提示詞中提供明確的參數邊界限制（例如設定字數上限）非常重要？", "type": "multiple_choice", "options": ["主要是為了幫助資料庫管理員節省伺服器硬碟中日益枯竭的儲存空間", "能有效避免語言模型給出過於龐大或不切實際的參數，導致後端程式執行崩潰", "為了讓開發出來的技能在名稱與說明文件上看起來更加符合專業的工業標準", "因為這是多數知名雲端平台在提供 API 服務時所要求的強制性資訊安全規定"], "correct_index": 1, "explanation": "明確的限制能防止代理人因為過度發散的想像力而產生導致系統錯誤的極端輸入。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7325, "chapter_title": "Agentic Skills 設計", "section_title": "記憶管理設計", "text": "在建立代理人的長期記憶管理系統時，導入向量資料庫最主要是為了解決什麼核心問題？", "type": "multiple_choice", "options": ["確保使用者在登入系統時輸入的密碼與權限能夠被最精確無誤地比對驗證", "透過將文字轉化為數學向量，實現語意層級的搜尋，快速召回最相關的歷史經驗", "用來穩定且大量地儲存使用者上傳的高解析度圖片、音訊檔案與高畫質影片資料", "為了完全取代電腦傳統的主記憶體 (RAM) 架構，從而大幅度降低系統建置的硬體成本"], "correct_index": 1, "explanation": "向量搜尋超越了傳統的關鍵字比對，讓代理人能理解概念上的相似性並找到對應記憶。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7326, "chapter_title": "Agentic Skills 設計", "section_title": "規劃策略設計", "text": "當具備「動態重規劃」能力的代理人在執行步驟中途遇到 API 呼叫失敗時，它通常會怎麼應對？", "type": "multiple_choice", "options": ["會立刻判定任務失敗，直接中斷所有背景程式並回報嚴重錯誤給終端使用者", "吸收失敗的錯誤訊息作為新上下文，重新思考並生成一條可能成功的全新解決路徑", "不考慮任何其他可能性，持續以極高的頻率不斷重複呼叫同一個 API 直到成功為止", "假裝沒看到錯誤，直接忽略這個失敗的關鍵步驟，並強行跳到計畫中的最後一個步驟"], "correct_index": 1, "explanation": "動態重規劃的精髓在於保持目標不變，但通往目標的路徑可以根據現實狀況靈活調整。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7327, "chapter_title": "Agentic Skills 設計", "section_title": "Skill 設計最佳實踐", "text": "開發者在替代理人撰寫工具的自然語言描述 (Description) 時，最應當遵守的指導原則是什麼？", "type": "multiple_choice", "options": ["必須鉅細靡遺地詳列出該工具在後端伺服器中的所有程式碼實作邏輯與細節", "應該清楚且精確地說明這個工具「能達成什麼目的」以及「在什麼情境下該被使用」", "為了顯示開發團隊的技術實力，盡量在說明中塞滿各種深奧且難懂的業界專有名詞", "為了節省語言模型處理的 token 數量，務必將所有描述的總字數嚴格控制在十個字以內"], "correct_index": 1, "explanation": "模型不需要知道底層怎麼實作，只需要知道什麼時候用它、用了會有什麼效果。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7328, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "「上下文修剪 (Context Pruning)」技術通常被應用於解決代理人的哪一種內部問題？", "type": "multiple_choice", "options": ["當代理人需要產生極度冗長的文章時，用來限制其最大輸出字數的控制機制", "當新獲得的資訊與舊有記憶產生嚴重矛盾時，主動移除或覆寫已過時的歷史資訊", "當代理人發現自己的程式碼架構過於老舊時，自動向版本控制系統發送的更新請求", "當系統的硬碟儲存空間即將耗盡時，自動對所有的多媒體檔案進行深度破壞性壓縮"], "correct_index": 1, "explanation": "修剪過時與矛盾的資訊能確保模型在推理時有一個乾淨、邏輯一致的上下文基礎。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
    {"id": 7329, "chapter_title": "Agentic Skills 設計", "section_title": "上下文工程 (Context Engineering)", "text": "在處理極度複雜的任務時，提供給模型一個「暫存區 (Scratchpad)」可以帶來什麼顯著的好處？", "type": "multiple_choice", "options": ["確保每一次的對話記錄都會被永久保存到不可竄改的去中心化區塊鏈網路上", "賦予模型一段不被使用者直接看見的「思考空間」，以利其整理邏輯、拆解步驟與協調衝突", "能夠自動將模型思考過程中所產生的任何有趣見解，直接發布更新到外部的社群媒體平台上", "透過跳過所有複雜的推理步驟直接輸出預設答案，來大幅降低大型語言模型的整體運算成本"], "correct_index": 1, "explanation": "暫存區如同人類的計算紙，先寫下推理過程再給出最終答案，能大幅提升準確率。", "tags": ["chap-m5-ch3"], "usage": "quiz"},
]

append_qs('chapter1.yaml', ch1_qs)
append_qs('chapter2.yaml', ch2_qs)
append_qs('chapter3.yaml', ch3_qs)
print("Finished appending 1, 2, and 3")
